apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  loadBalancerIP: 192.168.0.50
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000